_wandb:
    value:
        cli_version: 0.23.1
        e:
            3cdv2fv5tvlv5azj5hxl2485fhszom34:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: /Users/dhruv/code/Machine Learning/Projects/Deeplearning-Project/project/index.ipynb
                codePathLocal: index.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "467455352832"
                email: dhruvrana4@gmail.com
                executable: /Users/dhruv/code/Machine Learning/Projects/Deeplearning-Project/.venv/bin/python
                git:
                    commit: 44a0d609a2309486c73145e88ff0e80c2868c78c
                    remote: git@github.com:Dhruvrana8/Deeplearning-Project.git
                host: Dhruvs-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/dhruv/code/Machine Learning/Projects/Deeplearning-Project/project/index.ipynb
                python: CPython 3.11.14
                root: /Users/dhruv/code/Machine Learning/Projects/Deeplearning-Project/project
                startedAt: "2025-12-08T20:37:54.937702Z"
                writerId: 3cdv2fv5tvlv5azj5hxl2485fhszom34
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
